### ISSUE TITLE
Download Page has expired certificate.

### ISSUE THREAD

**Issue by Jawastew** [librevault/librevault#106]
Just wanted to let you know your *.librevault.com cert seems to be expired.

https://releases.librevault.com/windows/librevault_latest.exe

**Comment by Mattias1** [comment]
`Err:4 https://releases.librevault.com/debian bionic Release                    
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 2600:9000:2002:da00:16:5:f2c0:93a1 443]`
