### ISSUE TITLE
No updates in over a year - project still active?

### ISSUE THREAD

**Issue by jd666** [librevault/librevault#107]

**Comment by LeadManPL** [comment]
@heyakyra : seems like not totally dead ;)

Anyway, anybody know some alternatives to this project?

 I know
* Sia
* StorJ
* Filecoin.io

but all of them are blockchain based and keep all versioning history. I would need rather simple P2P solution with Zero Knowledge, rent my HDD space to others and get some space from others.

**Comment by saviodsouza** [comment]
Go syncthing.net

**Comment by Astuceman** [comment]
https://alternativeto.net/software/librevault/
Find there something good

**Comment by GamePad64** [comment]
Librevault is in the state of total rewrite now. All the major features will be kept, but some will be replaced by other.
For example, network stack may be replaced with [libp2p](https://github.com/libp2p/rust-libp2p).
