### ISSUE TITLE
Librevault has a Virus !

### ISSUE THREAD

**Issue by deonsebastiandk** [librevault/librevault#196]
Hello ! I am a LibreVault user . so to check it out i downloaded the LibreVault installer for windows from Github because the download link in the official website is broken . so after sometime the installer was downloaded the i checked the installer for viruses in virustotal.com . the results are Surprising ! It said it had two types of malware detected by 2 Antimalware software . 1. ESET-NOD32 2 . Qihoo-360 . Result from ESET-NOD32 - A Variant Of Win32/MiniUPnP.C Potentially Unsafe  Result from Qihoo-360 - HEUR/QVM06.1.0000.Malware.Gen   . Here is the Virustotal report - https://www.virustotal.com/gui/file/9bf0748e248a93cf3e1a42e6bdcc9cfba41fa5247cf78331561df8f72fea1d7c/detection . Please fix this issue as soon as possible .

**Comment by GamePad64** [comment]
Hi!
It looks like a false positive. Miniupnpc is just a component for NAT Traversal, it is completely harmless.
