### ISSUE TITLE
Add readme file

### ISSUE THREAD

**Issue by denix666** [Librevault/librevault#21]
Hello,
Please add the minimal readme file with info how to compile and install this software from the source.
Thank you!

**Comment by misuzu** [comment]
How-to on Ubuntu/Debian packaging would also be nice.

**Comment by GamePad64** [comment]
Added basic build instructions for Linux:
https://github.com/Librevault/librevault/blob/master/docs/build.md

It covers special instructions for installing dependencies for Ubuntu 15.10+

**Comment by GamePad64** [comment]
I am packaging for different versions of Debian/Ubuntu automatically using Jenkins.
First, it produces a tarball, publishes it [here](https://releases.librevault.com/sources/).
Then, it unpacks it, clones [this repository](https://github.com/Librevault/librevault-debian) into `debian/` directory and writes a new `debian/changelog` file (yes, instead of putting a new item into an existing file)
and invokes debuild (pdebuild, actually).
It produces `librevault` (which is a GUI package) and `librevault-daemon` packages.

**Comment by GamePad64** [comment]
Added Readme.md

**Comment by misuzu** [comment]
@GamePad64 Why not just move debian stuff to main repository and use native packaging (so you can build without intercourse with orig tarballs)?

**Comment by GamePad64** [comment]
@misuzu Orig tarballs are also useful for building RPM, PKGBUILD and others. Also, Debian documentation suggests using "3.0 (quilt)" format even in Debian-native packages.

**Comment by misuzu** [comment]
@GamePad64 Debian files doesn't conflict with RPM or PKGBUILD, librevault tarball can be downloaded from releases page. Debian recommendation is for debian maintainers for usage in their repository with their own ```debian``` files. Outside of their repository quilt is a pain in the ass. If you worried that your ```debian``` files will conflict with their ```debian``` files (if they will add librevault to their repo) you can rename ```debian``` to ```deb``` and make script for  copying ```deb``` to ```debian``` and adding ```changelog```. This would be really useful for anybody who want to build your package from git.

**Comment by GamePad64** [comment]
> Outside of their repository quilt is a pain in the ass

Yes, it is. I am not planning to create and maintain quilt-style patches.
> If you worried that your debian files will conflict with their debian files (if they will add librevault to their repo) you can rename debian to deb and make script for copying deb to debian and adding changelog

Makes sense to me. Syncthing developers did the same, btw:
https://github.com/syncthing/syncthing/issues/3099

I will move librevault-debian repository contents to `packaging/debian` folder and create a script, that moves it back into `debian`, and creates changelog file.

**Comment by GamePad64** [comment]
Well, this change is breaking current build system (on Jenkins). It was originally created for a tar-based workflow (test if building->make tar->make deb/rpm/whatever). It would require a major overhaul of all the building process. I will leave this change for a bit later and apply it in the process of adding Fedora/Arch builder to my build server.
