### ISSUE TITLE
Release source tarbolls

### ISSUE THREAD

**Issue by derlaft** [Librevault/librevault#34]
Right now, there's no available .tar.gz with the latest version.

As the easiest way, you can use github releases (just bind them for release tags and it will generate .tar.gz and .zip for you).

This would make packaging it in linux distros much easier.

**Comment by derlaft** [comment]
Oh, I am blind. Sorry (:

**Comment by GamePad64** [comment]
There are tarballs at https://releases.librevault.com/sources/
