### ISSUE TITLE
.ignore file support

### ISSUE THREAD

**Issue by GamePad64** [Librevault/librevault#37]
Ignored files should be defined in a separate `.ignore` file. It is the common approach between Git (`.gitignore`), BTSync (`.IgnoreList`), Syncthing (`.stignore`) and many other systems.

**Comment by jaredreich** [comment]
This is definitely one of the most important features for me!

**Comment by GamePad64** [comment]
Added experimental support in 06b3b3f318a84a474d31a76173e623ec0698ac4e. Needs testing.

**Comment by GamePad64** [comment]
I have written a [wiki page](https://github.com/Librevault/librevault/wiki/Ignore-file-syntax) with ignore file syntax description.
