### ISSUE TITLE
Crashes on launch on OSX

### ISSUE THREAD

**Issue by aaronpk** [Librevault/librevault#38]
I just downloaded the OSX version and it crashes on launch. Here is the crash report: https://gist.github.com/aaronpk/eea9335c67da93b2d4b49dbf7ffb4343

**Comment by GamePad64** [comment]
Hmm.. I've tested 0.1.17 on OS X, but had nothing like this. It crashes on Protocol Buffers initialization code. Maybe, you can try to install build [0.1.18.4](https://releases.librevault.com/mac/librevault_v0.1.18.4.dmg). It has a newer version of Protobuf and is built on a dedicated OSX 10.11.6 build server. It should work well.

**Comment by aaronpk** [comment]
That one works, thanks!
