### ISSUE TITLE
LibreVault is "stuck" on windows

### ISSUE THREAD

**Issue by KrisZane** [Librevault/librevault#43]
So I saw someone suggest this whole LibreVault thing, and I would have to say it is a great initiative and a much sorely needed combination of an opensource folder sharing tool, combined with a good looking UI (Syncthing is kind of ugly, heavy and hard to use and well "BTSync" is just plainly terrible when not in paid version).

So on to the actual problem, my program seems to be entirely stuck, as in it will start up and I won't be able to add any folders, nor change any settings, basically not able to do anything.

I've tried wiping the config directory to do a "reset", but with no change to the result.

The log isn't much helpful with this either:
```
[2016-08-11 08:45:45.738709] [T:3144] [I] Librevault 0.1.17
[2016-08-11 08:45:45.741748] [T:3144] [D] Public key: 03EBD315DEFABD25C1243474DA770A8B72EE1F1CEC7D0853493A95DAAD8D9B7D35
[2016-08-11 08:45:45.834984] [T:3144] [T] [NATPMPService] initnatpmp() = 0
```

Do tell me if you require more information. :)

**Comment by elrac** [comment]
I'm having exactly the same issue, folders don't appear in the main window, settings will not save. I'm in windows 10 with the anniversary update.

**Comment by tscs37** [comment]
I got the same issue on Arch x64.

Freshly build from source, no settings are saving, folders do not appear in the window and only on the first startup connections to the network where made.

Log files do not show any errors. 

Console output of the GUI:

```
==>  QJsonDocument({"command":"add_folder","folder":{"path":"/home/<user>/projects/other/librevault/build/gui","secret":""}})
```

**Comment by GamePad64** [comment]
The `[T] [NATPMPService] initnatpmp() = 0` issue is related to NAT-PMP initialization. NAT-PMP initialization blocked on UPNP_GetValidIGD(). It have been rewritten with in 02472a2584cd6905573e29f13a92492adb08f9fe.
