### ISSUE TITLE
Add license information.

### ISSUE THREAD

**Issue by ZoomRmc** [Librevault/librevault#44]
It's unclear under what license the code is open. I couldn't find the information neither here nor the official site.
Is it still an open question, or just the information is lacking? Hope it is/will be properly copylefted.

**Comment by GamePad64** [comment]
This issue was resolved in #22. The licence file is named COPYING.
The code in licenced under the terms of GPLv3. It *is* properly copylefted :wink:

Also, all used libraries with their licences are defined in https://github.com/Librevault/librevault/blob/master/docs/dependencies.md

**Comment by ZoomRmc** [comment]
Oops, sorry, missed the COPYING file. Anyway, you should probably mention it in Readme and the Site. Thumbs up for the choice!
