### ISSUE TITLE
Feature request: allow setting up untrusted peers / servers

### ISSUE THREAD

**Issue by mrbiber** [Librevault/librevault#48]
It would be great if one could set up a peer to synchronize a set of folders without being able to decrypt the content. This would enable users to use non-trusted servers for backup/synchronization across devices that are never online at the same time without divulging their secrets.

It would allow people to offer provable zero-knowledge hosting/backup based on Librevault and thus offer an opportunity to build businesses around the protocol without compromising security (which could also, long-term provide funding for development).

See syncthing/syncthing#109 for a related feature request in Syncthing.

**Comment by GamePad64** [comment]
[Secret type D](https://github.com/Librevault/librevault/wiki/Secret-Structure#secret-type) is exactly what you are looking for. It is already implemented in Librevault client.

**Comment by mrbiber** [comment]
I see, that's pretty great (a bit hard to discover, though ;-) ). Thanks very much!
