### ISSUE TITLE
Password is logged in clear text

### ISSUE THREAD

**Issue by rasb23** [Librevault/librevault#59]
When debugging a folder I noticed that the secret is logged in clear text. 
==>  QJsonDocument({"command":"add_folder","folder":{"path":"/","secret":"thepassword"}})

Is this for alpha testing? Will this secret not be displayed in a final release?

On: ubuntu-mate 16.04

**Comment by GamePad64** [comment]
The final release will certainly not log any passwords (unencrypted paths, delta hashes, Secrets) or any other data, that may compromise your security. The logging system will be reformed to log confidential data into a separate stream, so you could decide if you want to share your private data or not (this is not necessary in most cases).

But, your case is not about logging in daemon. It is about logging in GUI. This logging is completely not necessary in release builds and will be removed from them ASAP.

**Comment by GamePad64** [comment]
Removed qDebug output in Release builds.
