### ISSUE TITLE
librevault-daemon opens too many incomplete files and crashes

### ISSUE THREAD

**Issue by interfect** [Librevault/librevault#61]
On Ubuntu 16.04, librevault-daemon 0.1.18 crashes after doing a bit of indexing, like this:

```
[2016-08-28 11:39:53.504716] [T:14359] [W] [WSService] void librevault::WSService::on_tcp_post_init(WSClass&, websocketpp::connection_hdl) [with WSClass = websocketpp::server<librevault::asio_tls>; websocketpp::connection_hdl = std::weak_ptr<void>] e:Certificate error
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  use_certificate_file: Too many open files
Aborted (core dumped)
```

I have also observed:

```
terminate called without an active exception
Aborted (core dumped)
```

Running `lsof -p <daemon PID>` shows hundreds of `.librevault/incomplete-BLABLABLA` files being opened by the daemon. Presumably it's exhausting its ulimits on open files because it;s forgetting to close them.

**Comment by interfect** [comment]
Deleting those files from the .libvrevault directory doesn't help. It just recreates them.

**Comment by GamePad64** [comment]
Well, now all `incomplete-` files are managed automatically, opening and closing on demand. Current limit is 100 `incomplete-` files per daemon. The limit is hard-coded. If you need a config entry, please, notify me.
