### ISSUE TITLE
OpenSSL is incompatible with the GPL

### ISSUE THREAD

**Issue by davexunit** [Librevault/librevault#62]
Hello,

I was trying to write a LibreVault package recipe for GNU Guix and noticed that LibreVault depends on OpenSSL.  Unfortunately, the OpenSSL license is incompatible with the GPL [0].   One possible solution would be to replace OpenSSL with GnuTLS.

[0] https://people.gnome.org/~markmc/openssl-and-the-gpl.html

**Comment by msva** [comment]
by the way, it does not affect source based distributions like Gentoo, SourceMage, whatsoever

**Comment by davexunit** [comment]
@msva: That doesn't change the fact that there is a licensing violation.  The LibreVault website itself distributes binaries.

**Comment by GamePad64** [comment]
@davexunit Thank you for addressing this issue. The idea of replacing OpenSSL with GnuTLS is tempting but nearly impossible for one person to implement. The thing is, is that Librevault depends on libraries, that depend on OpenSSL (boost.asio, websocket++, Qt), and I can't rewrite their SSL backends to use GnuTLS or any other SSL library.

So, now I am going to use *another* possible solution: adding OpenSSL linking exception. It may harm the GPL "purity", but this is the only practical solution now.

Btw, OpenSSL guys [announced changing their license to Apache License version 2](https://www.openssl.org/blog/blog/2015/08/01/cla/) about a year ago, so, maybe, in the future, this exception will not be necessary at all.
