### ISSUE TITLE
Client does not connect to daemon

### ISSUE THREAD

**Issue by mikken** [Librevault/librevault#75]
Trying to launch the gui part:
```
$ librevault-gui 
Connecting to:  QUrl("ws://[::1]:42346")
Connecting to daemon:  QUrl("ws://[::1]:42346")
Disconnected from daemon:  QUrl("ws://[::1]:42346")  Reason:  "Connection timed out"
```
Also, error message box pops up: `Problem running Librevault service: Connection timed out`.
Connections to/from localhost are always allowed in my firewall (nftables).
In system log there's this message:
```
kernel: TCP: request_sock_TCPv6: Possible SYN flooding on port 42346. Dropping request.  Check SNMP counters.
```

This is Librevault 0.1.18.11 running in Gentoo.
There are no errors in librevault.log and I can see the opened [::1]:42346 listening socket in netstat.
Same kernel message appears if I launch librevault-daemon manually and telnet to it.

**Comment by GamePad64** [comment]
Well, I have tested it on my Ubuntu machine today and I couldn't reproduce this error. Something in the kernel just blocks all requests to this port... Changing the port to something else doesn't help, does it?

**Comment by mikken** [comment]
I don't know, `globals.json` file contains only `null` string.
I tried with this config instead:
```
{
   "control_port" : "[::]:30000"
}
```
But it still listens on 42346.
No problems occur with netcat6:
```
$ nc6 -l -p 42346 -s ::1
nc6: using stream socket
hello from client
```

**Comment by GamePad64** [comment]
The name of config entry is `control_listen`, not `control_port`. It is strange, that netcat can connect to this port, but telnet can't. Maybe, there is some sort of bug in websocket++.

**Comment by mikken** [comment]
Confirmed that changing listen port does not help.
The above command runs netcat6 in server mode and I connect to it with telnet.
Thus, netcat6 acts as librevault-daemon. I also tried without binding to ::1 IP address.
I use Qt 5.6.1.

**Comment by mikken** [comment]
I also tried compiling with system websocketpp 0.7.0 instead of bundled.
With websocketpp 0.6.0 it didn't compile.

**Comment by mikken** [comment]
I found something similar: https://github.com/zaphoyd/websocketpp/issues/549

**Comment by mikken** [comment]
It works now once I updated websocketpp to Git's `develop` branch..
Maybe the bundled version should be patched, too.

**Comment by GamePad64** [comment]
Yes. Thank you, very much. I have updated websocket++ to develop branch in current commit. Next version will be bundled with a fixed version of websocket++.
