### ISSUE TITLE
CLion "compatible"?

### ISSUE THREAD

**Issue by aadrian** [librevault/librevault#97]
Please make the project(s) "CLion compatible", i.e. to use CMake for **all** the parts.

AFAIK CLion https://www.jetbrains.com/clion/ is free for open source projects. The smart editing, refactoring and debugging features work only if the project is 100% is cmake covered :( .

Thank you.

**Comment by GamePad64** [comment]
The project is compatible with CLion right now. I use it for the further development

**Comment by aadrian** [comment]
@GamePad64 

> I use it for the further development

Any chance sharing those CLion project files in the Git Repo too? 

Jetbrains products now allow sharing those in a directory independent manner:
https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems

Thank you.
