### ISSUE TITLE
Development status

### ISSUE THREAD

**Issue by baimafeima** [librevault/librevault#99]
What's the current development status of librevault? The last tagged release was almost a year ago. Would be great to see your project succeed. Is this still alpha software?

**Comment by thekyriarchy** [comment]
You're looking at the wrong branch (as was I), but all the action is in the development branch: https://github.com/Librevault/librevault/tree/develop

**Comment by thekyriarchy** [comment]
@GamePad64 how are things? notice it's been a month since any changes to the dev branch

**Comment by catb0t** [comment]
@thekyriarchy one-two months of silence is nothing to worry about for most open source projects, to be honest

**Comment by shadadougha** [comment]
@thekyriarchy checking in to see how progress is going as it’s been silent for a bit.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mikken** [comment]
I'm worried, too.
I hope we'll see a release this year.

**Comment by almereyda** [comment]
This community could suggest to create an https://opencollective.com/ page to support the Librevault development, or https://liberapay.com/.

**Comment by saviodsouza** [comment]
Hi

Is this project alive

**Comment by heyakyra** [comment]
Forums are down for me and the last reply was a year ago saying the rewrite in QT was almost complete: 
https://webcache.googleusercontent.com/search?q=cache:lFVnOJt8q-oJ:https://forum.librevault.com/t/is-this-project-abandoned/138/9

Maybe if someone else could pick up development @GamePad64 would be willing to pass this on to them?

**Comment by LeadManPL** [comment]
Is anyone able to estimate, how much money would be sufficient to finish development?

Maybe some fund rising would be possible...

**Comment by GamePad64** [comment]
Librevault is in the state of total rewrite now. All the major features will be kept, but some will be replaced by other.
For example, network stack may be replaced with libp2p.

**Comment by heyakyra** [comment]
Any updates on this? 

I wonder if https://github.com/servio-rs/servio is part of the rewrite, or if this is abandoned. 

Maybe someone can bulid something on top of [DataLad](https://www.datalad.org/) (powered by [git-annex](https://git-annex.branchable.com/)) which could even be the foundation for an open source [Abstract](https://www.abstract.com/) alternative. 

There's also [Named Data Networking](https://en.wikipedia.org/wiki/Named_data_networking) which long-predates IPFS and from what I understand seems to be more well thought out overall.

There's also the Hypercore Protocol (formerly Dat Protocol) by [Holepunch](https://holepunch.to/) but that's mostly for web apps.
